sudo: required
language: java
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
env:
  - PGVERSION=8.4
  - PGVERSION=9.0
  - PGVERSION=9.1
  - PGVERSION=9.2
  - PGVERSION=9.3
  - PGVERSION=9.4
install: ./.travis/travis-install-dependencies
script: ant test
after_failure: ./.travis/print_surefire_reports
